# pyproject.toml
# This file defines the project configuration using the PEP 621 standard for CrewAI.

[project]
name = "traffic-violation-crew"
version = "0.1.0"
description = "A CrewAI project for monitoring traffic violations on edge devices."
authors = [
    { name = "AI Assistant", email = "assistant@example.com" },
]
dependencies = [
    "crewai>=0.28.8",
    "crewai-tools>=0.1.5",
    "python-dotenv>=1.0.0",
    "chromadb>=0.4.22",
]
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# This new section explicitly tells the build system which files to include.
[tool.hatch.build.targets.wheel]
include = [
    "main.py",
    "agents.py",
    "tasks.py",
    "tools/",
] 